name: "🐛 Bug report"
description: "Something isn’t working as expected"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!  
        Please fill out **all** required fields.

  - type: input
    id: summary
    attributes:
      label: "Short summary"
      placeholder: "Crash when clicking Connect"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      placeholder: |
        1. Go to …
        2. Click …
        3. Observe …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behaviour"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behaviour"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      placeholder: |
        - OS: 
        - Browser:  
        - Angular app version: 
        - Electron app verison: 

  - type: checkboxes
      id: self_assign
      attributes:
        label: "Will you implement this yourself?"
        options:
          - label: "Yes – assign this issue to me"
            required: false
